services:
  redis:
    image: redis:alpine3.19
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  worker:
    command: ['celery', 'worker', '-A', 'leonosaurus', '-l', 'info']
    environment:
      - BROKER_URL=redis://localhost:6379/0
    volumes:
      - ./src:/src
    depends_on:
      - rabbitmq
      - redis

volumes:
  redis:
    driver: local
