services:
  redis:
    image: redis:alpine3.19
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  backend:
    image: lujeni/leonosaurus:latest
    restart: always
    command: >
      bash -c "python /app/src/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    image: lujeni/leonosaurus:latest
    command: >
      bash -c "cd /app/src && celery -A leonosaurus worker"
    env_file:
      - .env
    volumes:
      - ./src:/app/src/
    depends_on:
      - redis
      - backend

volumes:
  redis:
    driver: local
