services:
  redis:
    image: redis:alpine3.19
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  backend:
      build: .
      tty: true
      command: >
        bash -c "python /app/manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./src:/app/src/
      ports:
        - "8000:8000"
      depends_on:
        - redis

  worker:
    build: .
    command: >
      bash -c "cd /app/src && celery -A leonosaurus worker"
    environment:
      - BROKER_URL=redis://localhost:6379/0
    volumes:
      - ./src:/app/src/
    depends_on:
      - redis
      - backend

volumes:
  redis:
    driver: local
