[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "leonosaurus"
version = "0.0.1"
dependencies = [
  "Django==5.0.2",
  "psycopg2-binary==2.9.9",
  "django-allauth==0.61.1",
]

[project.optional-dependencies]
dev = [
  "black",
  "django-stubs",
  "ipdb",
  "ruff",
  "pre-commit",
]
