# Generated by Django 5.0.2 on 2024-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deploydocus", "0002_gitlabproject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scope",
            old_name="exlude",
            new_name="exclude",
        ),
        migrations.AlterField(
            model_name="scope",
            name="include",
            field=models.CharField(default=".*", max_length=300),
        ),
    ]
