# Generated by Django 5.0.2 on 2024-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploydocus", "0003_rename_exlude_scope_exclude_alter_scope_include"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabproject",
            name="merge_method",
            field=models.CharField(
                choices=[("merge", "Merge")], default="merge", max_length=30
            ),
            preserve_default=False,
        ),
    ]
