# Generated by Django 5.0.2 on 2024-02-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deploydocus", "0004_gitlabproject_merge_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabproject",
            name="merge_method",
            field=models.CharField(
                choices=[
                    ("ff", "Ff"),
                    ("merge", "Merge"),
                    ("rebase_merge", "Rebase Merge"),
                ],
                max_length=30,
            ),
        ),
    ]
