# Generated by Django 5.0.2 on 2024-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploydocus", "0007_policy_gitlab_rules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gitlabrule",
            options={
                "ordering": ["name"],
                "verbose_name": "GitLab Rule",
                "verbose_name_plural": "GitLab Rules",
            },
        ),
        migrations.AddField(
            model_name="gitlabrule",
            name="expected",
            field=models.CharField(default="merge", max_length=300),
            preserve_default=False,
        ),
    ]
