# Generated by Django 5.0.2 on 2024-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploydocus", "0009_alter_policy_gitlab_rules_alter_policy_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="scope",
            name="gitlab_projects",
            field=models.ManyToManyField(blank=True, to="deploydocus.gitlabproject"),
        ),
    ]
