# Generated by Django 5.0.4 on 2024-05-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deploydocus", "0010_scope_gitlab_projects"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportresult",
            options={
                "ordering": ["report"],
                "verbose_name": "Report result",
                "verbose_name_plural": "Report results",
            },
        ),
        migrations.RemoveField(
            model_name="reportresult",
            name="status",
        ),
    ]
